name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Build binaries
      run: |
        mkdir -p dist
        if [ "${{ matrix.goos }}" = "windows" ]; then
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/ssmssh_${{ matrix.goos }}_${{ matrix.goarch }}.exe .
        else
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/ssmssh_${{ matrix.goos }}_${{ matrix.goarch }} .
        fi

    - name: Create archive
      run: |
        cd dist
        if [ "${{ matrix.goos }}" = "windows" ]; then
          zip ssmssh_${{ matrix.goos }}_${{ matrix.goarch }}.zip ssmssh_${{ matrix.goos }}_${{ matrix.goarch }}.exe
        else
          tar -czf ssmssh_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz ssmssh_${{ matrix.goos }}_${{ matrix.goarch }}
        fi

    - name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/ssmssh_*.tar.gz
          dist/ssmssh_*.zip
